version: '3.8'
services:
  json-server:
    container_name: json-server-cont
    build:
      context: ./
    image: test-user:v1
    command: json-server --watch db.json --host 0.0.0.0 --port 3001
    ports:
      - "3001:3001"

  frontend:
    container_name: frontend-cont
    build:
      context: ./
    image: test-user:v1
    command: npm start
    ports:
      - "3000:3000"